### ISSUE TITLE
Can't  launch node-OpenDroneMap

### ISSUE THREAD

**Issue by coulibalyIsmael** [OpenDroneMap/node-OpenDroneMap#2]
Hi,
After succesful achieved all the processes  to launch node-OpenDroneMap locally , When I trie to launch: `node index.js`
 this error occurs: 
`home/user/OpenDroneMap-0.2/node-OpenDroneMap/libs/Task.js:37
	constructor(uuid, name, done, options = []){
	                                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/OpenDroneMap-0.2/node-OpenDroneMap/libs/TaskManager.js:25:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
`
Please help me.
Thanks.

**Comment by pierotofy** [comment]
Hi @coulibalyIsmael,

I'm guessing that your version of node is lower than 6.

```
[piero@acer opendronemap]$ node --version
v7.5.0
```

Make sure that your version of node is >= 6.0. Let me know if you have questions about upgrading it.

**Comment by coulibalyIsmael** [comment]
After the nodeJS update it works fine. Thanks
